# Generated by Django 4.1.3 on 2022-12-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='service',
            name='date',
            field=models.DateField(verbose_name='service date'),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('O', 'Oil Change'), ('B', 'Service Brakes'), ('A', 'Change Filters')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='car',
            name='accessories',
            field=models.ManyToManyField(to='main_app.accessory'),
        ),
    ]
